name: Build, Deploy, and Trigger API

on:
  push:
    branches:
      - dev  # Cambia a la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR via SFTP
        id: upload_step
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          # Instala sshpass para autenticar la sesión
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Ruta al archivo JAR
          JAR_FILE="target/ReuneMe.jar"
          if [ -f "$JAR_FILE" ]; then
            echo "Uploading $JAR_FILE to SFTP server..."

            # Nombre del archivo en el servidor
            REMOTE_FILE="ReuneMe.jar"

            # Crea un archivo temporal con los comandos sftp
            echo "-rm $REMOTE_FILE" > sftp_commands.txt
            echo "put $JAR_FILE $REMOTE_FILE" >> sftp_commands.txt

            # Usa sshpass y sftp para ejecutar los comandos
            if sshpass -p "$SFTP_PASSWORD" sftp -o StrictHostKeyChecking=no -P "$SFTP_PORT" -b sftp_commands.txt "$SFTP_USER@$SFTP_HOST"; then
              echo "UPLOAD_SUCCESS=true" >> $GITHUB_ENV  # Guarda éxito en el entorno
            else
              echo "SFTP upload failed!"
              exit 1
            fi
          else
            echo "No JAR file found!"
            exit 1
          fi

      - name: Trigger API on Successful Upload
        if: env.UPLOAD_SUCCESS == 'true'
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          API_KEY: ${{ secrets.API_KEY }}
          PTEROSERVER: ${{ secrets.PTEROSERVER }}
        run: |
          echo "Triggering API to start server..."
          curl -k "https://$SFTP_HOST/api/client/servers/$PTEROSERVER/power" \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $API_KEY" \
            -X POST \
            -d '{
              "signal": "restart"
            }'
